package homeLibrary.entity;
// Generated 04.10.2012 22:18:59 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Authors generated by hbm2java
 */
public class Authors  implements java.io.Serializable {


     private Integer authorId;
     private String authorName;
     private Set booksAuthorses = new HashSet(0);

    public Authors() {
    }

	
    public Authors(String authorName) {
        this.authorName = authorName;
    }
    public Authors(String authorName, Set booksAuthorses) {
       this.authorName = authorName;
       this.booksAuthorses = booksAuthorses;
    }
   
    public Integer getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }
    public String getAuthorName() {
        return this.authorName;
    }
    
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }
    public Set getBooksAuthorses() {
        return this.booksAuthorses;
    }
    
    public void setBooksAuthorses(Set booksAuthorses) {
        this.booksAuthorses = booksAuthorses;
    }




}


